version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - model
    environment:
      - MONGO_URI=mongodb://mongo:27017/dev
      - MODEL_SERVICE_URL=http://model:5000

  model:
    build: ./model_service
    ports:
      - "5000:5000"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
